name: Code Review

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: write

jobs:
  rubocop:
    name: RuboCop Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Run RuboCop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rspec:gemfile rubocop-rake:gemfile
          reporter: github-pr-review
          fail_level: any

  reek:
    name: Reek Code Smells
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Reek
        uses: reviewdog/action-reek@v1
        with:
          reek_version: gemfile
          reporter: github-pr-review
          fail_level: any
